baseURL = "/"
relativeURLs = true

locale = "vi-VN"
title = "SOVRA Portal"
theme = "hugo-book-main"

[params]
  BookFavicon = "images/icon.jpg"
  BookLogo = "images/icon.jpg"
  BookTheme = "auto"
  BookToC = true
  BookSection = "*"
  BookSearch = true

[markup.goldmark.renderer]
  unsafe = true
